# -*- coding: utf-8 -*-
from flask import Flask

DEBUG = False
SQLALCHEMY_ECHO = False
SQLALCHEMY_POOL_RECYCLE = 280
SQLALCHEMY_POOL_SIZE = 20
SQLALCHEMY_TRACK_MODIFICATIONS = True
PER_PAGE = 32
UPLOAD_URL = 'static/upload'
PREVIEW_THUMBNAIL = '-preview'
